In [1]:
import pandas as pd
import numpy as np

In [2]:
# get pandas version
pd.__version__

'3.0.6'

In [3]:
# read csv file
df = pd.read_csv('../data/car_fuel_efficiency_2026.csv')

In [4]:
# few values from the csv
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [5]:
# number of records in the file
len(df)

10000

In [6]:
# fuel types
df['fuel_type'].nunique()

3

In [7]:
# how many columns missing values
df.isnull().any().sum()

np.int64(2)

In [8]:
# max fuel efficiency
df['fuel_efficiency_mpg'].max()

np.float64(41.2)

In [9]:
# median value of horsepower
median_value = df['horsepower'].median()
median_value

np.float64(254.0)

In [10]:
# most frequent value in horsepower column
freq_horsepower = df['horsepower'].mode()[0]
freq_horsepower

np.float64(252.0)

In [11]:
# fill missing horsepower with most freq horsepower
df['horsepower'] = df['horsepower'].fillna(freq_horsepower)

In [12]:
# new median
new_median_value = df['horsepower'].median()
new_median_value

np.float64(252.0)

In [13]:
if new_median_value > median_value:
    print('increased')
elif new_median_value < median_value:
    print('decreased')
else:
    print('no change')

decreased

In [14]:
# select all asian cars
asian_cars = df[df['origin'] == 'Asia']
asian_cars.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,252.0,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4

In [15]:
# select only vehicle_weight and model_year
new_df = asian_cars[['vehicle_weight','model_year']]
new_df

      vehicle_weight  model_year
2               4240        1996
6               4310        1992
8               4230        1997
10              4420        1978
15              3950        2007
...              ...         ...
9984            4610        2011
9987            4530        2004
9990            3630        1975
9994            4610        1993
9996            4370        1993

[2994 rows x 2 columns]

In [16]:
# select first 7 values
new_df = new_df.head(n=7)
new_df

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [17]:
# get underlying numpy array
X = new_df.values
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [18]:
# X transpose
XT = X.T
XT

array([[4240, 4310, 4230, 4420, 3950, 4750, 4450],
       [1996, 1992, 1997, 1978, 2007, 2021, 2019]])

In [19]:
# matrix-matrix multiplication XT and X
XTX = XT.dot(X)
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [20]:
# invert XTX
invert_XTX = np.linalg.inv(XTX)
invert_XTX

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [21]:
# new array y with given values
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [22]:
# multiply inverser of XTX and transpose of X
w = (invert_XTX.dot(XT)).dot(y)
w

array([0.13644777, 0.2327492 ])

In [23]:
# sum of all elements
w.sum()

np.float64(0.3691969690492547)